let obj = {
  Afghanistan: { name: "Afghanistan", dial_code: "+93", code: "AF" },
  Albania: { name: "Albania", dial_code: "+355", code: "AL" },
  Algeria: { name: "Algeria", dial_code: "+213", code: "DZ" },
  Andorra: { name: "Andorra", dial_code: "+376", code: "AD" },
  Angola: { name: "Angola", dial_code: "+244", code: "AO" },
  "Antigua and Barbuda": {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
  },
  Argentina: { name: "Argentina", dial_code: "+54", code: "AR" },
  Armenia: { name: "Armenia", dial_code: "+374", code: "AM" },
  Aruba: { name: "Aruba", dial_code: "+297", code: "AW" },
  Australia: { name: "Australia", dial_code: "+61", code: "AU" },
  Austria: { name: "Austria", dial_code: "+43", code: "AT" },
  Azerbaijan: { name: "Azerbaijan", dial_code: "+994", code: "AZ" },
  Bahamas: { name: "Bahamas", dial_code: "+1242", code: "BS" },
  Bahrain: { name: "Bahrain", dial_code: "+973", code: "BH" },
  Bangladesh: { name: "Bangladesh", dial_code: "+880", code: "BD" },
  Barbados: { name: "Barbados", dial_code: "+1246", code: "BB" },
  Belarus: { name: "Belarus", dial_code: "+375", code: "BY" },
  Belgium: { name: "Belgium", dial_code: "+32", code: "BE" },
  Belize: { name: "Belize", dial_code: "+501", code: "BZ" },
  "Bosnia and Herzegovina": {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
  },
  Botswana: { name: "Botswana", dial_code: "+267", code: "BW" },
  Brazil: { name: "Brazil", dial_code: "+55", code: "BR" },
  Bulgaria: { name: "Bulgaria", dial_code: "+359", code: "BG" },
  Cambodia: { name: "Cambodia", dial_code: "+855", code: "KH" },
  Cameroon: { name: "Cameroon", dial_code: "+237", code: "CM" },
  Canada: { name: "Canada", dial_code: "+1", code: "CA" },
  "Cayman Islands": { name: "Cayman Islands", dial_code: "+ 345", code: "KY" },
  Chile: { name: "Chile", dial_code: "+56", code: "CL" },
  China: { name: "China", dial_code: "+86", code: "CN" },
  Colombia: { name: "Colombia", dial_code: "+57", code: "CO" },
  Congo: { name: "Congo", dial_code: "+242", code: "CG" },
  "Costa Rica": { name: "Costa Rica", dial_code: "+506", code: "CR" },
  Croatia: { name: "Croatia", dial_code: "+385", code: "HR" },
  Cuba: { name: "Cuba", dial_code: "+53", code: "CU" },
  Cyprus: { name: "Cyprus", dial_code: "+357", code: "CY" },
  "Czech Republic": { name: "Czech Republic", dial_code: "+420", code: "CZ" },
  Denmark: { name: "Denmark", dial_code: "+45", code: "DK" },
  "Dominican Republic": {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
  },
  Ecuador: { name: "Ecuador", dial_code: "+593", code: "EC" },
  Egypt: { name: "Egypt", dial_code: "+20", code: "EG" },
  "El Salvador": { name: "El Salvador", dial_code: "+503", code: "SV" },
  Estonia: { name: "Estonia", dial_code: "+372", code: "EE" },
  "Faroe Islands": { name: "Faroe Islands", dial_code: "+298", code: "FO" },
  Finland: { name: "Finland", dial_code: "+358", code: "FI" },
  France: { name: "France", dial_code: "+33", code: "FR" },
  "French Polynesia": {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
  },
  Gabon: { name: "Gabon", dial_code: "+241", code: "GA" },
  Georgia: { name: "Georgia", dial_code: "+995", code: "GE" },
  Germany: { name: "Germany", dial_code: "+49", code: "DE" },
  Ghana: { name: "Ghana", dial_code: "+233", code: "GH" },
  Greece: { name: "Greece", dial_code: "+30", code: "GR" },
  Greenland: { name: "Greenland", dial_code: "+299", code: "GL" },
  Guadeloupe: { name: "Guadeloupe", dial_code: "+590", code: "GP" },
  Guam: { name: "Guam", dial_code: "+1671", code: "GU" },
  Guatemala: { name: "Guatemala", dial_code: "+502", code: "GT" },
  Guinea: { name: "Guinea", dial_code: "+224", code: "GN" },
  Haiti: { name: "Haiti", dial_code: "+509", code: "HT" },
  Honduras: { name: "Honduras", dial_code: "+504", code: "HN" },
  "Hong Kong": { name: "Hong Kong", dial_code: "+852", code: "HK" },
  Hungary: { name: "Hungary", dial_code: "+36", code: "HU" },
  Iceland: { name: "Iceland", dial_code: "+354", code: "IS" },
  India: { name: "India", dial_code: "+91", code: "IN" },
  Indonesia: { name: "Indonesia", dial_code: "+62", code: "ID" },
  Iraq: { name: "Iraq", dial_code: "+964", code: "IQ" },
  Ireland: { name: "Ireland", dial_code: "+353", code: "IE" },
  "Isle of Man": { name: "Isle of Man", dial_code: "+44", code: "IM" },
  Israel: { name: "Israel", dial_code: "+972", code: "IL" },
  Italy: { name: "Italy", dial_code: "+39", code: "IT" },
  Jamaica: { name: "Jamaica", dial_code: "+1876", code: "JM" },
  Japan: { name: "Japan", dial_code: "+81", code: "JP" },
  Kazakhstan: { name: "Kazakhstan", dial_code: "+77", code: "KZ" },
  Kenya: { name: "Kenya", dial_code: "+254", code: "KE" },
  Kuwait: { name: "Kuwait", dial_code: "+965", code: "KW" },
  Latvia: { name: "Latvia", dial_code: "+371", code: "LV" },
  Lebanon: { name: "Lebanon", dial_code: "+961", code: "LB" },
  Liechtenstein: { name: "Liechtenstein", dial_code: "+423", code: "LI" },
  Luxembourg: { name: "Luxembourg", dial_code: "+352", code: "LU" },
  Macedonia: { name: "Macedonia", dial_code: "+389", code: "MK" },
  Madagascar: { name: "Madagascar", dial_code: "+261", code: "MG" },
  Malaysia: { name: "Malaysia", dial_code: "+60", code: "MY" },
  Malta: { name: "Malta", dial_code: "+356", code: "MT" },
  Martinique: { name: "Martinique", dial_code: "+596", code: "MQ" },
  Mauritius: { name: "Mauritius", dial_code: "+230", code: "MU" },
  Mayotte: { name: "Mayotte", dial_code: "+262", code: "YT" },
  Mexico: { name: "Mexico", dial_code: "+52", code: "MX" },
  Mongolia: { name: "Mongolia", dial_code: "+976", code: "MN" },
  Montenegro: { name: "Montenegro", dial_code: "+382", code: "ME" },
  Morocco: { name: "Morocco", dial_code: "+212", code: "MA" },
  Mozambique: { name: "Mozambique", dial_code: "+258", code: "MZ" },
  Namibia: { name: "Namibia", dial_code: "+264", code: "NA" },
  Nepal: { name: "Nepal", dial_code: "+977", code: "NP" },
  Netherlands: { name: "Netherlands", dial_code: "+31", code: "NL" },
  "New Caledonia": { name: "New Caledonia", dial_code: "+687", code: "NC" },
  "New Zealand": { name: "New Zealand", dial_code: "+64", code: "NZ" },
  Nicaragua: { name: "Nicaragua", dial_code: "+505", code: "NI" },
  Nigeria: { name: "Nigeria", dial_code: "+234", code: "NG" },
  Norway: { name: "Norway", dial_code: "+47", code: "NO" },
  Oman: { name: "Oman", dial_code: "+968", code: "OM" },
  Pakistan: { name: "Pakistan", dial_code: "+92", code: "PK" },
  Panama: { name: "Panama", dial_code: "+507", code: "PA" },
  "Papua New Guinea": {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
  },
  Paraguay: { name: "Paraguay", dial_code: "+595", code: "PY" },
  Peru: { name: "Peru", dial_code: "+51", code: "PE" },
  Philippines: { name: "Philippines", dial_code: "+63", code: "PH" },
  Poland: { name: "Poland", dial_code: "+48", code: "PL" },
  Portugal: { name: "Portugal", dial_code: "+351", code: "PT" },
  "Puerto Rico": { name: "Puerto Rico", dial_code: "+1939", code: "PR" },
  Romania: { name: "Romania", dial_code: "+40", code: "RO" },
  Russia: { name: "Russia", dial_code: "+7", code: "RU" },
  "Saint Lucia": { name: "Saint Lucia", dial_code: "+1758", code: "LC" },
  "San Marino": { name: "San Marino", dial_code: "+378", code: "SM" },
  "Saudi Arabia": { name: "Saudi Arabia", dial_code: "+966", code: "SA" },
  Senegal: { name: "Senegal", dial_code: "+221", code: "SN" },
  Serbia: { name: "Serbia", dial_code: "+381", code: "RS" },
  Singapore: { name: "Singapore", dial_code: "+65", code: "SG" },
  Slovakia: { name: "Slovakia", dial_code: "+421", code: "SK" },
  Slovenia: { name: "Slovenia", dial_code: "+386", code: "SI" },
  "South Africa": { name: "South Africa", dial_code: "+27", code: "ZA" },
  Spain: { name: "Spain", dial_code: "+34", code: "ES" },
  "Sri Lanka": { name: "Sri Lanka", dial_code: "+94", code: "LK" },
  Sudan: { name: "Sudan", dial_code: "+249", code: "SD" },
  Suriname: { name: "Suriname", dial_code: "+597", code: "SR" },
  Swaziland: { name: "Swaziland", dial_code: "+268", code: "SZ" },
  Sweden: { name: "Sweden", dial_code: "+46", code: "SE" },
  Switzerland: { name: "Switzerland", dial_code: "+41", code: "CH" },
  Taiwan: { name: "Taiwan", dial_code: "+886", code: "TW" },
  Thailand: { name: "Thailand", dial_code: "+66", code: "TH" },
  "Trinidad and Tobago": {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
  },
  Tunisia: { name: "Tunisia", dial_code: "+216", code: "TN" },
  Turkey: { name: "Turkey", dial_code: "+90", code: "TR" },
  Ukraine: { name: "Ukraine", dial_code: "+380", code: "UA" },
  "United Arab Emirates": {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
  },
  "United Kingdom": { name: "United Kingdom", dial_code: "+44", code: "GB" },
  "United States": { name: "United States", dial_code: "+1", code: "US" },
  Uruguay: { name: "Uruguay", dial_code: "+598", code: "UY" },
  Vietnam: { name: "Vietnam", dial_code: "+84", code: "VN" },
  Zambia: { name: "Zambia", dial_code: "+260", code: "ZM" },
  Zimbabwe: { name: "Zimbabwe", dial_code: "+263", code: "ZW" },
};
